
import cuid from 'cuid'

/**
 * Redux Mock Store State for DEV
 **/

/**
 * INITIAL STATE OF APPLICATION
 **/

const mockState = {
    appState: {
        deviceDetails: null,
        sidebarOpen: false,
        isFetching: false,
    },
    deviceDetails: null,
    sidebarOpen: false,
    // -- state --
    navbar: {
        activeBadge: 0,
    },
    // -- content --
    likes: [
        {
            id: cuid(),
            itemid: 123,
            type: "post",
            title: "Post title here, if available",
            content: "Post content here",
            src: null,
            userid: 2,
            username: "Gonzales",
            avatar: '/img/avatar/face-13.jpg',
            timestamp: 1501229377,
        },
        {
            id: cuid(),
            itemid: 124,
            type: "thread",
            title: "Thread 222 title here, if available",
            content: "Post 222 content here",
            src: null,
            userid: 9,
            username: "Joe",
            avatar: '/img/avatar/face-4.jpg',
            timestamp: 1501229577,
        },
        {
            id: cuid(),
            itemid: 125,
            type: "image",
            title: "AlbumImage title here, if available",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            userid: 9,
            username: "Joe",
            avatar: '/img/avatar/face-4.jpg',
            timestamp: 1501229577,
        }
    ],
    notifications: [
        {
            id: cuid(),
            type: "message",
            userid: 3,
            username: "Gamel, John J.",
            avatar: "/img/avatar/face.jpg",
            title: "Brunch this weekend?",
            content: "I&apos;ll be in your neighborhood doing errands this weekend. Do you want to grab brunch?",
            timestamp: 1502788349,
        },
        {
            id: cuid(),
            type: "quota",
            title: "System Message",
            content: "Quota exceeded",
            timestamp: 1502788549,
        },
        {
            id: cuid(),
            type: "message",
            userid: 3,
            username: "Gamel, John J.",
            avatar: "/img/avatar/face.jpg",
            title: "Hello???",
            content: "...",
            timestamp: 1502789349,
        },
    ],
    updates: [
        {
            id: cuid(),
            type: "image",
            primaryText: "Brunch this weekend?",
            secondaryText: "I&apos;ll be in your neighborhood doing errands this weekend. Do you want to grab brunch?",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            fromUsername: "Brandan Lim",
            avatar: "/img/avatar/face-1.jpg",
            timestamp: 1501229377,
        },
        {
            id: cuid(),
            type: "post",
            primaryText: "Oui oui",
            secondaryText: "Do you have Paris recommendations? Have you ever been?",
            fromUsername: "Grace Ng",
            avatar: "/img/avatar/face-2.jpg",
            timestamp: 1501229177,
        },
        {
            id: cuid(),
            type: "image",
            primaryText: "Birdthday gift",
            secondaryText: "Do you have any ideas what we can get Heidi for her birthday? How about a pony?",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            fromUsername: "Kerem Suer",
            avatar: "/img/avatar/face-3.jpg",
            timestamp: 1501229077,
        },
        {
            id: cuid(),
            type: "image",
            primaryText: "Recipe to try",
            secondaryText: "We should eat this: grated squash. Corn and tomatillo tacos.",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            fromUsername: "Raquel Parrado",
            avatar: "/img/avatar/face-4.jpg",
            timestamp: 1501220077,
        },
        {
            id: cuid(),
            type: "like",
            primaryText: "Brunch this weekend?",
            secondaryText: "I&apos;ll be in your neighborhood doing errands this weekend. Do you want to grab brunch?",
            fromUsername: "Brandan Lim",
            avatar: "/img/avatar/face-5.jpg",
            timestamp: 1501200077,
        },
        {
            id: cuid(),
            type: "post",
            primaryText: "Oui oui",
            secondaryText: "Do you have Paris recommendations? Have you ever been?",
            fromUsername: "Grace Ng",
            avatar: "/img/avatar/face-6.jpg",
            timestamp: 1501000077,
        },
        {
            id: cuid(),
            type: "post",
            primaryText: "Birdthday gift",
            secondaryText: "Do you have any ideas what we can get Heidi for her birthday? How about a pony?",
            fromUsername: "Kerem Suer",
            avatar: "/img/avatar/face-7.jpg",
            timestamp: 1501000057,
        },
        {
            id: cuid(),
            type: "video",
            primaryText: "Recipe to try",
            secondaryText: "We should eat this: grated squash. Corn and tomatillo tacos.",
            thumb: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            fromUsername: "Raquel Parrado",
            avatar: "/img/avatar/face-8.jpg",
            timestamp: 1500000057,
        },
    ],
    threads: [],
    posts: [
        {
            id: cuid(),
            title: "Cars & Dinos",
            content: "Dinosaurs are like cars.",
            username: "Joe",
            userid: 9,
            tags: ["cars", "thread-123"],
            timestamp: 1501135362,
        },
        {
            id: cuid(),
            title: "Dinos & Cars",
            content: "Cars are like dinosaurs.",
            username: "Moe",
            userid: 10,
            tags: ["dinosaurs", "thread-123"],
            timestamp: 1501185342,
        },
        {
            id: cuid(),
            title: "Testing the Forums",
            content: "Forums are like dinosaurs.",
            username: "Toe",
            userid: 11,
            tags: ["forums", "dinosaurs", "thread-124"],
            timestamp: 1501188342,
        },
        {
            id: cuid(),
            title: "Testing the Dinos",
            content: "Dinos are like forums.",
            username: "Hogo",
            userid: 12,
            tags: ["forums", "dinosaurs", "thread-124"],
            timestamp: 1501198342,
        },
    ],
    post: {
        id: cuid(),
        title: "Testing the Dinos",
        content: "Dinos are like forums.",
        username: 'Anonymous',
        userid: 0,
        tags: ["forums", "dinosaurs", "thread-124"],
        timeStamp: Math.round(Date.now() / 1000), // Unix Timestamp in seconds
    },
    albums: [],
    album: [
        {
            title: "1 Mock 1 image 1 title",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            timestamp: 1501239377,
        },
        {
            title: "Mock 222 image title",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            timestamp: 1501239377,
        },
        {
            title: "Mock 333 image title",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            timestamp: 1501239377,
        },
        {
            title: "444 Mock image title",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            timestamp: 1501239377,
        },
        {
            title: "Mock image title 555",
            src: "https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg",
            timestamp: 1501239377,
        }
    ],
    messageHistory: {
        username: "Gonzales",
        userid: 2,
        messages: [
            {
                id: cuid(),
                username: "Gonzales",
                userid: 2,
                avatar: '/img/avatar/face-13.jpg',
                msg: "Wassup, [b]homie[/b]?",
                timestamp: 1501229377,
            },
            {
                id: cuid(),
                username: "me",
                userid: 1,
                avatar: '/img/avatar/face.jpg',
                msg: "wha?",
                timestamp: 1501229387,
            },
            {
                id: cuid(),
                username: "Gonzales",
                userid: 2,
                avatar: '/img/avatar/face-13.jpg',
                msg: "[quote]wha?[/quote][i]wassss[/i]uuuuup?",
                timestamp: 1501239377,
            },
            {
                id: cuid(),
                username: "me",
                userid: 1,
                avatar: '/img/avatar/face.jpg',
                msg: "wassssuuuuup?",
                timestamp: 1501249377,
            },
            {
                id: cuid(),
                username: "Gonzales",
                userid: 2,
                avatar: '/img/avatar/face-13.jpg',
                msg: "...uuuuu...",
                timestamp: 1501259377,
            },
            {
                id: cuid(),
                username: "me",
                userid: 1,
                avatar: '/img/avatar/face.jpg',
                msg: "...uuuuu...",
                timestamp: 1501269377,
            },
            {
                id: cuid(),
                username: "me",
                userid: 1,
                avatar: '/img/avatar/face.jpg',
                msg: "...uuuuup?!",
                timestamp: 1501279377,
            },
        ]
    },
    reviewitem: {
        id: cuid(),
        primaryText: "Brunch this weekend?",
        secondaryText: "I&apos;ll be in your neighborhood doing errands this weekend. Do you want to grab brunch?",
        fromUsername: "Brandan Lim",
        fromUserid: 123,
        approvals: 0,
        disapprovals: 0,
        likes: 44,
        dislikes: 9,
        src: 'http://apod.nasa.gov/apod/image/1502/HDR_MVMQ20Feb2015ouellet1024.jpg',
        timestamp: 1501229377,
    },
    followers: [],
    dailyUploadLimits: {
        normal: {
            images: 1,
            videos: 1,
        }
    },
    users: {
        "1": {
            userid: 1,
            username: 'admin',
            hash: '239SAHJ#*HKDGB(#JDS)(U$WJ$KJDSJHOIDSHG*#J',
            avatar: '/img/avatar/face.jpg',
            profileimg: 'https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg',
            status: 'online',
            verifiedUser: false,
            dailyUploadLimitReached: false,
            lastActivity: 1502379924,
            // email: 'admin@thisdomain.com',
        },
        "2": {
            userid: 2,
            username: 'Gonzales',
            hash: 'fdiu39*U#UHDS*(#$HJKDJKHI#UHJKJKD',
            avatar: '/img/avatar/face-13.jpg',
            profileimg: 'https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg',
            status: 'offline',
            verifiedUser: true,
            dailyUploadLimitReached: false,
            lastActivity: 1502379924,
            // email: 'admin@thisdomain.com',
        },
    },
    currentUser: {
        userid: 1,
        username: 'admin',
        hash: '239SAHJ#*HKDGB(#JDS)(U$WJ$KJDSJHOIDSHG*#J',
        avatar: '/img/avatar/face.jpg',
        profileimg: 'https://apod.nasa.gov/apod/image/1705/ic410_WISEantonucci_960.jpg',
        status: 'online',
        verifiedUser: false,
        dailyUploadLimitReached: false,
        lastActivity: 1502379924,
        // email: 'admin@thisdomain.com',
    },
}

export default mockState
