
const routes = {
    HOME: "/",
    FORUM: "/forum",
    ALBUM: "/album",
    STREAM: "/stream",
    UPDATES: "/updates",
    NOTIFICATIONS: "/notifications",
    LIKES: "/likes",
    FAVORITES: "/favorites",
    PLAYLIST: "/playlist",
    PROFILE: "/profile",
    FOLLOWERS: "/followers",
    USERS: "/members",
    MEMBERS: "/members",
    POSTS: "/posts",
    IMAGES: "/images",
    VIDEOS: "/videos",
    SETTINGS: "/settings",
    REVIEW: "/review",
    EDIT: "/edit",
    MESSAGES: "/messages",
    CONTACT: "/contact",
    UPLOAD: "/upload",
    SIGNUP: "/signup",
    LOGIN: "/login",
    LOGOUT: "/logout",
    LEGAL: {
        COMMUNITY: "/community-guidelines",
        PRIVACY: "/privacy-policy",
        DMCA: "/dmca-policy",
    },
}

export default routes
