
const routes = {
    HOME: "/",
    FORUM: "/forum",
    ALBUM: "/album",
    STREAM: "/stream",
    UPDATES: "/updates",
    LIKES: "/likes",
    FAVORITES: "/favorites",
    PLAYLIST: "/playlist",
    PROFILE: "/profile",
    FOLLOWERS: "/followers",
    USERS: "/members",
    MEMBERS: "/members",
    POSTS: "/posts",
    THREADS: "/threads",
    CATEGORIES: "/categories",
    IMAGES: "/images",
    VIDEOS: "/videos",
    VERIFICATIONS: "/verifications",
    CHAT: "/chat",
    REVIEW: "/review",
    LEADERBOARD: "/leaderboard",
    EDIT: "/edit",
    MESSAGES: "/messages",
    CONTACT: "/contact",
    UPLOAD: "/upload",
    SIGNUP: "/signup",
    LOGIN: "/login",
    LOGOUT: "/logout",
    LEGAL: {
        INDEX: "/policy",
        COMMUNITY: "/community-guidelines",
        PRIVACY: "/privacy",
        DMCA: "/dmca",
    },
    SETTINGS: {
        INDEX: "/settings",
        ACCOUNT: "/account",
        AVATAR: "/avatar",
        GENERAL: "/general",
        IMAGE: "/image",
        VERIFICATION: "/verification",
        PRIVACY: "/privacy",
    },
    MODAREA: "/modarea",
}

export const PROFILE = routes.PROFILE

export default routes
